export const SET_SELECTED_CHARACTERS = "SET_SELECTED_CHARACTERS";
export const GET_AUDIO_OF_CONVERSATIONAL_MESSAGE_REQUEST =
  "GET_AUDIO_OF_CONVERSATIONAL_MESSAGE_REQUEST";
export const GET_AUDIO_OF_CONVERSATIONAL_MESSAGE_SUCCESS =
  "GET_AUDIO_OF_CONVERSATIONAL_MESSAGE_SUCCESS";
export const GET_AUDIO_OF_CONVERSATIONAL_MESSAGE_FAILURE =
  "GET_AUDIO_OF_CONVERSATIONAL_MESSAGE_FAILURE";
export const SET_EDITTED_MESSAGE_OF_CHARACTER_ONE =
  "SET_EDITTED_MESSAGE_OF_CHARACTER_ONE";
export const SET_EDITTED_MESSAGE_OF_CHARACTER_TWO =
  "SET_EDITTED_MESSAGE_OF_CHARACTER_TWO";
